manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: geeksville
      url-base: https://github.com/geeksville
    - name: beekeeb
      url-base: https://github.com/beekeeb
    - name: kureyakey
      url-base: https://github.com/kureyakey
    - name: sekigon-gonnoc
      url-base: https://github.com/sekigon-gonnoc
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
      revision: v0.3
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: v0.3
    - name: zmk-feature-non-lipo-battery-management
      remote: kureyakey
      revision: main
    - name: zmk_driver_azoteq
      remote: beekeeb
      revision: fix-3-finger
    - name: zmk-input-zoom
      remote: beekeeb
      revision: main
  self:
    path: config
